package it.chiarani.meteotrentinoapp.helper;

public enum WeatherTypes {
  SOLEGGIATO_CON_PIOGGIA,
  SOLEGGIATO_CON_PIOGGIA_E_NEVE,
  NEVICATA,
  SOLE,
  SOLEGGIATO,
  COPERTO,
  COPERTO_CON_PIOGGIA,
  COPERTO_CON_PIOGGIA_ABBONDANTE,
  COPERTO_CON_PIOGGIA_E_NEVE,
  TEMPORALE,
  UNDEFINED
}
